# Known or forbidden patterns to check on PBS.
# Format: TYPE|PATTERN|SEVERITY|MESSAGE
FORBIDDEN_MODULE_DEPENDENCY|openmpi/mlnx/gcc/64|WARN|Module depends on old openmpi/mlnx/gcc/64 stack
MISSING_ENV_VAR_PATTERN|INTELFPGAOCLSDKROOT|WARN|Module show references missing Intel FPGA OpenCL SDK variable
